apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml

commonLabels:
  app: webapp
  app.kubernetes.io/name: webapp
  app.kubernetes.io/managed-by: kustomize

commonAnnotations:
  description: "Flask web application"
