apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
    app.kubernetes.io/name: webapp
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: webapp
    tier: frontend
