apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    env: dev
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: dev
  labels:
    app: webapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: webapp
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: dev
  labels:
    app: webapp
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
      tier: frontend
  template:
    metadata:
      labels:
        app: webapp
        tier: frontend
    spec:
      containers:
      - name: webapp
        image: brkndocker/webapp:latest
        ports:
        - containerPort: 80
       