apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

patchesStrategicMerge:
  - replicas.yaml

configMapGenerator:
  - name: kustom-map-prod
    env: config.properties

replacements:
  - source:
      kind: ConfigMap
      name: kustom-map-prod
    targets:
      - select:
          kind: Deployment
        fieldPaths:
          - spec.template.spec.containers.*.envFrom.*.configMapRef.name
