name: Terraform & Bootstrap

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'infra/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:

      - name: Create GitHub App token
        id: app
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.GH_APPLICATION_ID }}
          private-key: ${{ secrets.GH_APP_KEY }}
          owner: ${{ github.repository_owner }}

      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/terraform-github-actions
          aws-region: eu-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init & Apply
        working-directory: infra
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Install argocd CLI
        run: |
          curl -sSL -o argocd \
            https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd && sudo mv argocd /usr/local/bin/

      - name: Run bootstrap
        run: bash bootstrap.sh
        env:
            GITHUB_TOKEN: ${{ steps.app.outputs.token }}